[project]
name = "kattis"
version = "0.1.0"
description = "learning poetry as trubleshoot with it in this folder"
authors = [
    {name = "Raouf",email = "khelfaoui.abderraouf@gmail.com"}
]
readme = "README.md"
homepage = "https://github.com/Abderaouf-KHELFAOUI/Poetry.git"
requires-python = ">=3.12"
dependencies = [
]

[tool.poetry]
packages = [{include = "kattis", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
